import type { AppData } from "../types";
import { calendarForYear } from "../lib/academic";
import { migrateData } from "../lib/recurrence";
export function fixture(): AppData {
  const cal = calendarForYear();
  return migrateData({
    rooms: [
      {
        id: "R1",
        room: "Workshop 1",
        campus: "Birmingham",
        building: "One",
        type: "Workshop",
        capacity: 30,
        status: "Available",
      },
      {
        id: "R2",
        room: "Workshop 2",
        campus: "Birmingham",
        building: "One",
        type: "Workshop",
        capacity: 30,
        status: "Available",
      },
    ],
    lecturers: [
      {
        id: "L1",
        name: "Alex",
        department: "Law",
        modules: ["LAW"],
        weeklyHours: 0,
        availability: "Mon-Fri 08:00-20:00",
        workload: "Normal",
        primaryCampus: "Birmingham",
        additionalCampuses: [],
        maxWeeklyHours: 18,
      },
      {
        id: "L2",
        name: "Blair",
        department: "Law",
        modules: ["LAW"],
        weeklyHours: 0,
        availability: "Mon-Fri 08:00-20:00",
        workload: "Normal",
        primaryCampus: "Birmingham",
        additionalCampuses: [],
        maxWeeklyHours: 18,
      },
    ],
    students: [
      {
        id: "U1",
        name: "Student One",
        campus: "Birmingham",
        programmeId: "P1",
        programme: "Law",
        moduleCodes: ["LAW"],
        status: "Active",
      },
    ],
    programmes: [
      {
        id: "P1",
        name: "Law",
        code: "LAW-P",
        campus: "Birmingham",
        academicYear: "2026/27",
        status: "Active",
      },
    ],
    modules: [
      {
        id: "M1",
        code: "LAW",
        name: "Law",
        course: "Law",
        campus: "Birmingham",
        programmeId: "P1",
        lecturerId: "L1",
        weeklySessions: 1,
        hoursPerSession: 2,
        roomTypeRequired: "Workshop",
      },
    ],
    studentGroups: [],
    requirements: [],
    sessions: [
      {
        id: "S1",
        day: "Monday",
        start: "09:00",
        end: "11:00",
        moduleCode: "LAW",
        moduleName: "Law",
        lecturer: "Alex",
        room: "Workshop 1",
        campus: "Birmingham",
        group: "",
        course: "Law",
        capacity: 30,
        enrolled: 1,
        studentIds: ["U1"],
        recurring: true,
        status: "Scheduled",
      },
    ],
    conflicts: [],
    templates: [
      {
        id: "T1",
        name: "Law workshop",
        moduleId: "M1",
        academicYearId: cal.year.id,
        campus: "Birmingham",
        programme: "Law",
        moduleCode: "LAW",
        moduleName: "Law",
        activityType: "Workshop",
        plannedSize: 1,
        durationHours: 2,
        weeklySessions: 1,
        teachingWeeks: [1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12],
        studentIds: ["U1"],
        studentGroup: "",
        lecturerSuitability: "Law",
        roomSuitability: "Workshop",
        preferredDays: "Mon",
        preferredTime: "Morning",
        publicationRule: "Standard",
        status: "Ready",
        updatedAt: "2026-09-01T00:00:00Z",
      },
    ],
  });
}
